name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
    - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
    - uses: actions/checkout@v2
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v0.0.1-preview
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_DUNE_046172F00 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: 'upload'
        app_location: '/'
        api_location: 'api'
        app_artifact_location: 'dist'
        api_build_command: 'yarn install'
      env:
          API_URL: ${{ secrets.API_URL }}
          APP_DESC: ${{ secrets.APP_DESC }}
          APP_NAME: ${{ secrets.APP_NAME }}
          BASE_URL: ${{ secrets.BASE_URL }}
          COSMOS_EP: ${{ secrets.COSMOS_EP }}
          COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
          COSMOS_DB: ${{ secrets.COSMOS_DB }}
          COSMOS_CONTAINER: ${{ secrets.COSMOS_CONTAINER }}